name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker HUb
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t zaid57/nodejs-app .
      - name: Publish Image to Docker Hub
        run: docker push zaid57/nodejs-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To EC2 Via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling Newest Image From Docker Hub"
            docker pull zaid57/nodejs-app:latest
            echo "Removing Existing Container"
            docker rm -f nodejs-app-container || true
            echo "Running New Container"
            docker run -d -p 5000:5000 --name nodejs-app-container zaid57/nodejs-app:latest
